/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.parisnanterre.neptune.backend;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class AppTest {

    @Test
    public void testMain() {
        // Checks that the main method doesn't throw an exception
        assertDoesNotThrow(() -> App.main(new String[] {}));
    }
}
