# Generated by Django 5.1.4 on 2025-01-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0011_groupmembership_moodgroup_groupmembership_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodgroup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
