# Generated by Django 5.1.4 on 2025-01-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0012_moodgroup_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
