# Generated by Django 5.1.4 on 2025-01-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0013_alter_moodgroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mood Ranking',
                'verbose_name_plural': 'Mood Rankings',
            },
        ),
    ]
