# Generated by Django 4.2.17 on 2025-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0015_remove_usermood_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermood',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
