# Generated by Django 5.1.4 on 2025-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0017_mapemoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='emoji',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
