# Generated by Django 5.1.4 on 2025-05-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0018_mood_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapemoji',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
    ]
