name: Django CI

on:                                    # mot clé pour QUAND l'action sera déclenché
  push:                                # déclendhé quand on push
    branches: [ "main", "develop" ]    # uniquement les push de main et develop
  pull_request:
    branches: [ "main" ]               # déclenché quand on pull-request

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest        # tourne sur dernière version ubuntu
    permissions:
      contents: read              # lire le contenu (code)
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13.0"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Build project
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List files
      run: ls -R

    # Test project
    - name: Run Tests
      run: |
        python manage.py test
      working-directory: ./moodapp

